### ISSUE TITLE
stuck executing, wont pass 85%

### ISSUE THREAD

**Issue by GuinnessShep** [Helltar/artific_intellig_bot#1]
> Task :run
38:07 INFO  Main [main] main: start ...
<===========--> 85% EXECUTING [40s]

**Comment by Helltar** [comment]
It's normal for gradle:

https://stackoverflow.com/questions/34724299/why-does-my-spring-boot-web-app-not-run-completely-in-gradle
https://stackoverflow.com/questions/26225728/gradle-application-plugin-stuck-at-96-when-runs-app

If your bot still don't work, check logs.
