### ISSUE TITLE
stuck at 85%

### ISSUE THREAD

**Issue by nagastone** [Helltar/artific_intellig_bot#3]
> Task :run
34:14 INFO  Main [main] main: start ...
WARNING: An illegal reflective access operation has occurred
### **WARNING: Illegal reflective access by retrofit2.Platform (file:/root/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.9.0/d8fdfbd5da952141a665a403348b74538efc05ff/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)**
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
<<===========--> 85% EXECUTING [14m 46s]
> :run

How can i fix this problem?Thank you very much!

**Comment by Helltar** [comment]
https://github.com/Helltar/artific_intellig_bot/issues/1
